packages:
  - packages/public/*
  - packages/personal/*
catalog:
  # ===
  # AVOID using catalog: on prod dependencies (for now), as Learn doesn't support it yet.
  # See https://github.com/lerna/lerna/issues/4055
  # ===
  '@testing-library/react': ^16.3.0
  '@types/jest': ^30.0.0
  '@types/node': ^22.18.6
  '@types/react': ^19.1.13
  '@types/react-dom': ^19.1.9
  eslint: ^8.57.1
  jest: ^30.1.3
  jest-environment-jsdom: ^30.1.2
  react: ^19.1.1
  react-dom: ^19.1.1
  ts-jest: ^29.4.4
  tsup: ^8.5.0
  typescript: ^5.9.2
onlyBuiltDependencies:
  - esbuild
  - nx
