packages:
  - packages/public/*
  - packages/personal/*
catalog:
  '@testing-library/react': ^16.3.2
  '@types/jest': ^30.0.0
  '@types/node': ^24.10.1
  '@types/react': ^19.2.14
  '@types/react-dom': ^19.2.3
  eslint: ^9.39.4
  react: ^19.2.5
  react-dom: ^19.2.5
  tsup: ^8.5.1
  typescript: ^6.0.3

  # Vite and Vitest
  '@vitejs/plugin-react': ^6.0.1
  '@vitest/coverage-v8': ^4.1.5
  vite: ^8.0.10
  vite-tsconfig-paths: ^6.1.1
  vitest: ^4.1.5
  unplugin-swc: ^1.5.9
  jsdom: ^29.0.2
onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - nx
  - unrs-resolver
