packages:
  - packages/public/*
  - packages/personal/*
catalog:
  '@testing-library/react': ^16.3.0
  '@types/jest': ^30.0.0
  '@types/node': ^24.10.1
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  eslint: ^9.39.1
  react: ^19.2.0
  react-dom: ^19.2.0
  tsup: ^8.5.1
  typescript: ^5.9.3

  # Vite and Vitest
  '@vitejs/plugin-react': ^5.1.1
  '@vitest/coverage-v8': ^4.0.14
  vite: ^7.2.6
  vite-tsconfig-paths: ^5.1.4
  vitest: ^4.0.14
  unplugin-swc: ^1.5.9
  jsdom: ^27.2.0
onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - nx
  - unrs-resolver
