import type globals from 'globals';
import type { ExtensionFragmentName, TestConvention } from './consts.js';

export type ConfigName = 'browser' | 'node';

export type RuleSettings = Record<string, unknown>;

/** Controls whether a named global can be reassigned. */
export type GlobalVarMode = 'readonly' | 'writable' | 'off';

/** Adds named globals and `$`-prefixed global groups from the `globals` package. */
export type GlobalVars = Partial<{
  [K in keyof typeof globals as `$${K}`]: true;
}> & {
  [key: string]: true | GlobalVarMode;
};

export type ResolvedGlobalVars = Record<string, boolean | string>;

/** Adds native Oxlint rules to a generated fragment without replacing its policy. */
export type ConfigFragment = {
  rules?: RuleSettings;
};

/** Overrides are keyed by the generated fragment they extend. */
export type ExtensionFragments = Partial<Record<ExtensionFragmentName, ConfigFragment>>;

/** Selects a test framework-specific native rule policy. */
export type TestFramework = 'vitest';

/**
 * Narrows a test override and optionally selects its environment, framework, and
 * TypeScript policy.
 */
export type TestConfigOptions = {
  configs?: ConfigName[];
  framework?: TestFramework;
  /** Uses a built-in convention or custom glob(s). */
  files?: TestConvention | (string & {}) | string[];
  ts?: boolean;
};

/** Selects both conventions, one built-in convention, or a custom test override. */
export type TestsOption = boolean | TestConvention | TestConfigOptions;

export type CreateConfigOptions = {
  configs: ConfigName[];
  extensions?: ExtensionFragments;
  globals?: GlobalVars;
  ignores?: string[];
  /** Enables the native subset of JSDoc policy. */
  jsdoc?: boolean;
  tests?: TestsOption;
  /** Defaults to `true`. */
  ts?: boolean;
  /**
   * Enables Oxlint's root-only type-aware mode. Requires oxlint-tsgolint and TypeScript
   * 7+.
   */
  typeAware?: boolean;
};

export type CreateReactConfigOptions = CreateConfigOptions;

export type CreateNextjsConfigOptions = Omit<CreateConfigOptions, 'configs' | 'ts'>;

export type CreateConfigSettings = CreateConfigOptions & {
  nextjs?: boolean;
  react?: boolean;
};

export type ResolveTestConfigOptions = {
  tests: TestsOption | undefined;
  productionConfig: ConfigName;
  productionTs: boolean;
};

export type ResolvedTestConfig = {
  configs: ConfigName[];
  files: string[];
  framework?: TestFramework;
  ts: boolean;
};

export type GeneratedConfigOverride = {
  files: string[];
  globals: ResolvedGlobalVars;
  rules: RuleSettings;
};

/** Native Oxlint configuration generated by this package's factories. */
export type GeneratedConfig = {
  globals: ResolvedGlobalVars;
  ignorePatterns?: string[];
  options?: {
    typeAware: true;
  };
  overrides?: GeneratedConfigOverride[];
  plugins: string[];
  rules: RuleSettings;
};

export type CreateTestOverrideOptions = {
  testConfig: ResolvedTestConfig;
  extensions?: ExtensionFragments;
  globals?: GlobalVars | ResolvedGlobalVars;
};

export type ResolveConfigComponentsOptions = Omit<CreateConfigSettings, 'globals'> & {
  testConfig?: ResolvedTestConfig;
  baseFragment?: ConfigFragment;
  baseExtensionFragment?: ConfigFragment;
  globals?: GlobalVars | ResolvedGlobalVars;
};

export type ResolveTestConfigComponentsOptions = {
  config: ConfigName;
  testConfig?: ResolvedTestConfig;
  tests?: TestsOption;
  ts?: boolean;
};

export type ResolveTestConfigComponentsResult = {
  doingTestsSetup: boolean;
  testConfig?: ResolvedTestConfig;
};

export type ResolveConfigComponentsResult = {
  config: ConfigName;
  globals: ResolvedGlobalVars;
  testConfig?: ResolvedTestConfig;
  fragments: ConfigFragment[];
  plugins: string[];
  configGlobals?: ResolvedGlobalVars;
};

export type ResolveGlobalsOptions = {
  globals?: GlobalVars | ResolvedGlobalVars;
  doingTestsSetup?: boolean;
};
