import type { ExtensionFragmentName, TestConvention } from './consts.js';

export type { ExtensionFragmentName } from './consts.js';

export type ConfigName = 'browser' | 'node';

export type RuleSettings = Record<string, unknown>;

/** Adds native Oxlint rules to a generated fragment without replacing its policy. */
export type ConfigFragment = {
  rules?: RuleSettings;
};

/** Overrides are keyed by the generated fragment they extend. */
export type ExtensionFragments = Partial<Record<ExtensionFragmentName, ConfigFragment>>;

/** Narrows a test override and optionally selects its environment and TypeScript policy. */
export type TestConfigOptions = {
  configs?: ConfigName[];
  files?: string | string[];
  ts?: boolean;
};

/** Selects both conventions, one built-in convention, or a custom test override. */
export type TestsOption = boolean | TestConvention | TestConfigOptions;

export type CreateConfigOptions = {
  configs: ConfigName[];
  extensions?: ExtensionFragments;
  ignores?: string[];
  /** Enables the native subset of JSDoc policy. */
  jsdoc?: boolean;
  tests?: TestsOption;
  ts?: boolean;
  /** Enables Oxlint's root-only type-aware mode. Requires oxlint-tsgolint and TypeScript 7+. */
  typeAware?: boolean;
};

export type CreateReactConfigOptions = CreateConfigOptions;

export type CreateNextjsConfigOptions = Omit<CreateConfigOptions, 'configs' | 'ts'>;

export type CreateConfigSettings = CreateConfigOptions & {
  nextjs?: boolean;
  react?: boolean;
};

export type ResolveTestConfigOptions = {
  tests: TestsOption | undefined;
  productionConfig: ConfigName;
  productionTs: boolean;
};

export type ResolvedTestConfig = {
  configs: ConfigName[];
  files: string[];
  ts: boolean;
};

export type GeneratedConfigOverride = {
  files: string[];
  globals: Record<string, boolean | string>;
  rules: RuleSettings;
};

/** Native Oxlint configuration generated by this package's factories. */
export type GeneratedConfig = {
  globals: Record<string, boolean | string>;
  ignorePatterns?: string[];
  options?: {
    typeAware: true;
  };
  overrides?: GeneratedConfigOverride[];
  plugins: string[];
  rules: RuleSettings;
};
