name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '18', '20' ]
    name: Run jest and ESLint (Node ${{ matrix.node }})
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - run: pnpm run lint:all
      - run: pnpm test
      - name: Coveralls for public/object-utils
        if: ${{ matrix.node == '18' }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: public-object-utils
          path-to-lcov: ./packages/public/object-utils/coverage/lcov.info
          base-path: ./packages/public/object-utils
      - name: Coveralls for public/deep-assign
        if: ${{ matrix.node == '18' }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: public-deep-assign
          path-to-lcov: ./packages/public/deep-assign/coverage/lcov.info
          base-path: ./packages/public/deep-assign
      - name: Coveralls for public/extend-promise
        if: ${{ matrix.node == '18' }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: public-extend-promise
          path-to-lcov: ./packages/public/extend-promise/coverage/lcov.info
          base-path: ./packages/public/extend-promise
      - name: Coveralls for public/jimple
        if: ${{ matrix.node == '18' }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: public-jimple
          path-to-lcov: ./packages/public/jimple/coverage/lcov.info
          base-path: ./packages/public/jimple
      - name: Coveralls for public/deferred
        if: ${{ matrix.node == '18' }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: public-deferred
          path-to-lcov: ./packages/public/deferred/coverage/lcov.info
          base-path: ./packages/public/deferred
      - name: Coveralls for public/events-hub
        if: ${{ matrix.node == '18' }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: public-events-hub
          path-to-lcov: ./packages/public/events-hub/coverage/lcov.info
          base-path: ./packages/public/events-hub
      - name: Coveralls for public/api-utils
        if: ${{ matrix.node == '18' }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: public-api-utils
          path-to-lcov: ./packages/public/api-utils/coverage/lcov.info
          base-path: ./packages/public/api-utils
      - name: Coveralls for public/path-utils
        if: ${{ matrix.node == '18' }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: public-path-utils
          path-to-lcov: ./packages/public/path-utils/coverage/lcov.info
          base-path: ./packages/public/path-utils
      - name: Coveralls for public/env-utils
        if: ${{ matrix.node == '18' }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: public-env-utils
          path-to-lcov: ./packages/public/env-utils/coverage/lcov.info
          base-path: ./packages/public/env-utils
      - name: Coveralls for public/package-info
        if: ${{ matrix.node == '18' }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: public-package-info
          path-to-lcov: ./packages/public/package-info/coverage/lcov.info
          base-path: ./packages/public/package-info
      - name: Coveralls for public/root-file
        if: ${{ matrix.node == '18' }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: public-root-file
          path-to-lcov: ./packages/public/root-file/coverage/lcov.info
          base-path: ./packages/public/root-file
      - name: Coveralls for public/simple-logger
        if: ${{ matrix.node == '18' }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: public-simple-logger
          path-to-lcov: ./packages/public/simple-logger/coverage/lcov.info
          base-path: ./packages/public/simple-logger
      - name: Coveralls for public/error-handler
        if: ${{ matrix.node == '18' }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: public-error-handler
          path-to-lcov: ./packages/public/error-handler/coverage/lcov.info
          base-path: ./packages/public/error-handler
      - name: Coveralls for public/simple-config
        if: ${{ matrix.node == '18' }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: public-simple-config
          path-to-lcov: ./packages/public/simple-config/coverage/lcov.info
          base-path: ./packages/public/simple-config
      - name: Coveralls for public/simple-storage
        if: ${{ matrix.node == '18' }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: public-simple-storage
          path-to-lcov: ./packages/public/simple-storage/coverage/lcov.info
          base-path: ./packages/public/simple-storage
      - name: Coveralls for public/fs-cache
        if: ${{ matrix.node == '18' }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: public-fs-cache
          path-to-lcov: ./packages/public/fs-cache/coverage/lcov.info
          base-path: ./packages/public/fs-cache
      - name: Coveralls for public/ts-async-import
        if: ${{ matrix.node == '18' }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: public-ts-async-import
          path-to-lcov: ./packages/public/ts-async-import/coverage/lcov.info
          base-path: ./packages/public/ts-async-import
      - name: Coveralls for public/react-ssr-config
        if: ${{ matrix.node == '18' }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: public-react-ssr-config
          path-to-lcov: ./packages/public/react-ssr-config/coverage/lcov.info
          base-path: ./packages/public/react-ssr-config

  finish:
      needs: build
      runs-on: ubuntu-latest
      steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
