name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '14', '16' ]
    name: Run jest and ESLint (Node ${{ matrix.node }})
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn --frozen-lockfile
      - run: yarn lint:all
      - run: yarn test
      - name: Coveralls (unit) for public/prettier-plugin-jsdoc
        if: ${{ matrix.node == '14' }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: public-prettier-plugin-jsdoc-unit
          path-to-lcov: ./packages/public/prettier-plugin-jsdoc/coverage-unit/lcov.info
          base-path: ./packages/public/prettier-plugin-jsdoc
      - name: Coveralls (e2e) for public/prettier-plugin-jsdoc
        if: ${{ matrix.node == '14' }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: public-prettier-plugin-jsdoc-e2e
          path-to-lcov: ./packages/public/prettier-plugin-jsdoc/coverage-e2e/lcov.info
          base-path: ./packages/public/prettier-plugin-jsdoc
      - name: Coveralls for public/object-utils
        if: ${{ matrix.node == '14' }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: public-object-utils
          path-to-lcov: ./packages/public/object-utils/coverage/lcov.info
          base-path: ./packages/public/object-utils
      - name: Coveralls for public/deep-assign
        if: ${{ matrix.node == '14' }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: public-deep-assign
          path-to-lcov: ./packages/public/deep-assign/coverage/lcov.info
          base-path: ./packages/public/deep-assign
      - name: Coveralls for public/extend-promise
        if: ${{ matrix.node == '14' }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: public-extend-promise
          path-to-lcov: ./packages/public/extend-promise/coverage/lcov.info
          base-path: ./packages/public/extend-promise
      - name: Coveralls for public/jimple
        if: ${{ matrix.node == '14' }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: public-jimple
          path-to-lcov: ./packages/public/jimple/coverage/lcov.info
          base-path: ./packages/public/jimple

  finish:
      needs: build
      runs-on: ubuntu-latest
      steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
